---
name:  ğŸ™‹â€â™‚ï¸â“ Ask for Help with Software Updates CLI with Apple
on: workflow_dispatch

jobs:
    macos-iso-create:
      name: ğŸ¤·â€â™‚ï¸ğŸ™‹â€â™‚ï¸â“ Run "Ask for help"
      runs-on: macos-13
      steps:
      - name: Ask for help â“
        run: softwareupdates --help
